-- Add sample vehicles for testing
-- This migration adds sample vehicles to the vehicles table for testing purposes

-- First, let's get a user ID to use for the vehicles
-- We'll use the first user from auth.users or create a test user reference

-- Insert sample vehicles
INSERT INTO public.vehicles (
    user_id,
    plate_number,
    plate_registration_type,
    serial_number,
    make_year,
    make_id,
    model_id,
    color_id,
    status_id,
    owner_id,
    actual_user_id,
    daily_rental_rate,
    monthly_rental_rate,
    hourly_rental_rate,
    mileage,
    car_class,
    form_license_expiration,
    insurance_policy_expiration,
    periodic_inspection_end,
    purchase_date,
    purchase_price,
    created_at,
    updated_at
) VALUES
(
    -- We'll use a placeholder user_id that should exist
    (SELECT id FROM auth.users LIMIT 1),
    'ABC-123',
    'Commercial',
    'VIN123456789',
    2022,
    (SELECT id FROM public.vehicle_makes WHERE name = 'Toyota' LIMIT 1),
    (SELECT id FROM public.vehicle_models WHERE name = 'Camry' LIMIT 1),
    (SELECT id FROM public.vehicle_colors WHERE name = 'White' LIMIT 1),
    (SELECT id FROM public.vehicle_statuses WHERE name = 'Available' LIMIT 1),
    (SELECT id FROM public.vehicle_owners LIMIT 1),
    (SELECT id FROM public.vehicle_actual_users LIMIT 1),
    150.00,
    4000.00,
    25.00,
    25000,
    'Sedan',
    '2025-12-31',
    '2025-06-30',
    '2025-03-31',
    '2022-01-15',
    80000.00,
    NOW(),
    NOW()
),
(
    (SELECT id FROM auth.users LIMIT 1),
    'XYZ-789',
    'Private',
    'VIN987654321',
    2021,
    (SELECT id FROM public.vehicle_makes WHERE name = 'Honda' LIMIT 1),
    (SELECT id FROM public.vehicle_models WHERE name = 'Civic' LIMIT 1),
    (SELECT id FROM public.vehicle_colors WHERE name = 'Black' LIMIT 1),
    (SELECT id FROM public.vehicle_statuses WHERE name = 'Rented' LIMIT 1),
    (SELECT id FROM public.vehicle_owners LIMIT 1),
    (SELECT id FROM public.vehicle_actual_users LIMIT 1),
    120.00,
    3200.00,
    20.00,
    35000,
    'Sedan',
    '2025-11-30',
    '2025-05-31',
    '2025-02-28',
    '2021-06-10',
    70000.00,
    NOW(),
    NOW()
),
(
    (SELECT id FROM auth.users LIMIT 1),
    'DEF-456',
    'Commercial',
    'VIN456789123',
    2023,
    (SELECT id FROM public.vehicle_makes WHERE name = 'Nissan' LIMIT 1),
    (SELECT id FROM public.vehicle_models WHERE name = 'Altima' LIMIT 1),
    (SELECT id FROM public.vehicle_colors WHERE name = 'Silver' LIMIT 1),
    (SELECT id FROM public.vehicle_statuses WHERE name = 'Available' LIMIT 1),
    (SELECT id FROM public.vehicle_owners LIMIT 1),
    (SELECT id FROM public.vehicle_actual_users LIMIT 1),
    140.00,
    3600.00,
    22.00,
    15000,
    'Sedan',
    '2026-01-31',
    '2025-07-31',
    '2025-04-30',
    '2023-03-20',
    75000.00,
    NOW(),
    NOW()
),
(
    (SELECT id FROM auth.users LIMIT 1),
    'GHI-012',
    'Private',
    'VIN012345678',
    2020,
    (SELECT id FROM public.vehicle_makes WHERE name = 'Hyundai' LIMIT 1),
    (SELECT id FROM public.vehicle_models WHERE name = 'Elantra' LIMIT 1),
    (SELECT id FROM public.vehicle_colors WHERE name = 'Blue' LIMIT 1),
    (SELECT id FROM public.vehicle_statuses WHERE name = 'Maintenance' LIMIT 1),
    (SELECT id FROM public.vehicle_owners LIMIT 1),
    (SELECT id FROM public.vehicle_actual_users LIMIT 1),
    100.00,
    2800.00,
    18.00,
    45000,
    'Sedan',
    '2025-09-30',
    '2025-04-30',
    '2025-01-31',
    '2020-08-15',
    65000.00,
    NOW(),
    NOW()
),
(
    (SELECT id FROM auth.users LIMIT 1),
    'JKL-345',
    'Commercial',
    'VIN345678901',
    2024,
    (SELECT id FROM public.vehicle_makes WHERE name = 'Ford' LIMIT 1),
    (SELECT id FROM public.vehicle_models WHERE name = 'Focus' LIMIT 1),
    (SELECT id FROM public.vehicle_colors WHERE name = 'Red' LIMIT 1),
    (SELECT id FROM public.vehicle_statuses WHERE name = 'Available' LIMIT 1),
    (SELECT id FROM public.vehicle_owners LIMIT 1),
    (SELECT id FROM public.vehicle_actual_users LIMIT 1),
    130.00,
    3400.00,
    21.00,
    8000,
    'Hatchback',
    '2026-03-31',
    '2025-08-31',
    '2025-05-31',
    '2024-01-10',
    72000.00,
    NOW(),
    NOW()
);

